using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System.Text;

namespace FellowshipAnalyzer.Generators;

/// <summary>
/// Emits a compile-time <c>HeroManifest</c> by scanning all referenced assemblies (plus the
/// current compilation) for classes carrying <c>[HeroAnalyzer]</c>. Also emits an
/// <c>AddFellowshipHeroAnalysis</c> DI extension that calls each hero's generated
/// <c>Add{Hero}Analysis()</c>. Triggered by a single class marked <c>[GenerateHeroManifest]</c>.
/// </summary>
[Generator]
public sealed class HeroManifestGenerator : IIncrementalGenerator
{
    private const string MarkerAttributeName = "GenerateHeroManifestAttribute";
    private const string HeroAnalyzerAttributeName = "HeroAnalyzerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var hosts = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, ct) => GetHostInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        var combined = hosts.Combine(context.CompilationProvider);
        context.RegisterSourceOutput(combined, static (ctx, pair) =>
        {
            var (host, compilation) = pair;
            Emit(ctx, host, compilation);
        });
    }

    private static bool IsCandidate(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDecl) return false;
        foreach (var attrList in classDecl.AttributeLists)
        foreach (var attr in attrList.Attributes)
        {
            var name = attr.Name.ToString();
            if (name == "GenerateHeroManifest" || name.EndsWith("GenerateHeroManifest") ||
                name == "GenerateHeroManifestAttribute" || name.EndsWith("GenerateHeroManifestAttribute"))
                return true;
        }
        return false;
    }

    private static HostInfo? GetHostInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
            return null;

        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.Name == MarkerAttributeName)
                return new HostInfo(symbol.Name, GetNamespace(symbol));
        }
        return null;
    }

    private static void Emit(SourceProductionContext ctx, HostInfo host, Compilation compilation)
    {
        var entries = new List<HeroEntry>();
        var seen = new HashSet<string>();

        CollectFromAssembly(compilation.Assembly, entries, seen);
        foreach (var reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assemblySymbol)
                CollectFromAssembly(assemblySymbol, entries, seen);
        }

        if (entries.Count == 0)
            return;

        entries.Sort((a, b) => string.CompareOrdinal(a.HeroEnumMember, b.HeroEnumMember));

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using FellowshipAnalyzer.Core.Analysis;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(host.Namespace))
        {
            sb.Append("namespace ").Append(host.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine("public sealed record HeroManifestEntry(global::FellowshipAnalyzer.Core.Analysis.HeroName Hero, string AssemblyName, Type ParserType, global::FellowshipAnalyzer.Core.Analysis.HeroConfig Config);");
        sb.AppendLine();

        sb.AppendLine("public static class HeroManifest");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<HeroManifestEntry> Entries { get; } =");
        sb.AppendLine("    [");
        foreach (var entry in entries)
        {
            sb.Append("        new HeroManifestEntry(global::FellowshipAnalyzer.Core.Analysis.HeroName.")
              .Append(entry.HeroEnumMember).Append(", \"").Append(entry.AssemblyName).Append("\", typeof(global::")
              .Append(entry.ParserTypeFullyQualified).Append("), ").Append(entry.ConfigAccessorFullyQualified).AppendLine("),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("public static class FellowshipHeroAnalysisServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers every discovered hero analyzer with DI. Generated from the compile-time");
        sb.AppendLine("    /// <c>HeroManifest</c>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddFellowshipHeroAnalysis(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var entry in entries)
        {
            sb.Append("        global::").Append(entry.ServiceCollectionExtensionFullyQualified)
              .Append(".Add").Append(entry.HeroEnumMember).AppendLine("Analysis(services);");
        }
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("HeroManifest.g.cs", sb.ToString());
    }

    private static void CollectFromAssembly(IAssemblySymbol assembly, List<HeroEntry> entries, HashSet<string> seen)
    {
        foreach (var type in GetAllNamedTypes(assembly.GlobalNamespace))
        {
            if (type.IsAbstract) continue;
            string? heroEnumMember = null;
            foreach (var attr in type.GetAttributes())
            {
                if (attr.AttributeClass?.Name != HeroAnalyzerAttributeName) continue;
                if (attr.ConstructorArguments.Length != 1) continue;
                var ctorArg = attr.ConstructorArguments[0];
                if (ctorArg.Type is not INamedTypeSymbol enumType || enumType.TypeKind != TypeKind.Enum) continue;
                foreach (var member in enumType.GetMembers())
                {
                    if (member is IFieldSymbol field && field.HasConstantValue && Equals(field.ConstantValue, ctorArg.Value))
                    {
                        heroEnumMember = field.Name;
                        break;
                    }
                }
                break;
            }

            if (heroEnumMember is null) continue;

            var parserTypeFq = ToFullyQualified(type);
            if (!seen.Add(parserTypeFq)) continue;

            var parserBaseName = StripSuffix(type.Name, "CombatLogParser");
            var ns = GetNamespace(type);
            var ext = string.IsNullOrEmpty(ns) ? parserBaseName + "ServiceCollectionExtensions"
                : ns + "." + parserBaseName + "ServiceCollectionExtensions";

            var configAccessor = "global::FellowshipAnalyzer.Core.Analysis.HeroConfig.Unmaintained";
            foreach (var member in type.GetMembers("HeroConfig"))
            {
                if (!member.IsStatic || member.DeclaredAccessibility != Accessibility.Public) continue;
                var memberType = member switch
                {
                    IPropertySymbol p => p.Type,
                    IFieldSymbol f => f.Type,
                    _ => null,
                };
                if (memberType is { Name: "HeroConfig" } &&
                    memberType.ContainingNamespace?.ToDisplayString() == "FellowshipAnalyzer.Core.Analysis")
                {
                    configAccessor = "global::" + parserTypeFq + ".HeroConfig";
                    break;
                }
            }

            entries.Add(new HeroEntry(
                HeroEnumMember: heroEnumMember,
                AssemblyName: assembly.Name,
                ParserTypeFullyQualified: parserTypeFq,
                ServiceCollectionExtensionFullyQualified: ext,
                ConfigAccessorFullyQualified: configAccessor));
        }
    }

    private static string StripSuffix(string name, string suffix) =>
        name.Length > suffix.Length && name.EndsWith(suffix)
            ? name.Substring(0, name.Length - suffix.Length)
            : name;

    private static string GetNamespace(INamedTypeSymbol symbol) =>
        symbol.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingNamespace.ToDisplayString()
            : string.Empty;

    private static string ToFullyQualified(INamedTypeSymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat
            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

    private static IEnumerable<INamedTypeSymbol> GetAllNamedTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            yield return type;
            foreach (var nested in type.GetTypeMembers())
                yield return nested;
        }
        foreach (var childNs in ns.GetNamespaceMembers())
        foreach (var type in GetAllNamedTypes(childNs))
            yield return type;
    }

    private sealed class HostInfo(string className, string ns)
    {
        public string ClassName { get; } = className; public string Namespace { get; } = ns;
    }

    private sealed class HeroEntry(string HeroEnumMember, string AssemblyName, string ParserTypeFullyQualified, string ServiceCollectionExtensionFullyQualified, string ConfigAccessorFullyQualified)
    {
        public string HeroEnumMember { get; } = HeroEnumMember;
        public string AssemblyName { get; } = AssemblyName;
        public string ParserTypeFullyQualified { get; } = ParserTypeFullyQualified;
        public string ServiceCollectionExtensionFullyQualified { get; } = ServiceCollectionExtensionFullyQualified;
        public string ConfigAccessorFullyQualified { get; } = ConfigAccessorFullyQualified;
    }
}
