using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using System.Collections.Immutable;
using System.Globalization;
using System.Text;

namespace FellowshipAnalyzer.Generators;

/// <summary>
/// For each hand-written <c>Talents</c> class under <c>FellowshipAnalyzer.Core.Common.Spells.{Hero}</c>,
/// emits a companion <c>{Hero}Talents</c> static class of <c>public const int &lt;Name&gt; = &lt;Id&gt;;</c>
/// members (one per static <c>Talent</c> property, using its <c>Id</c> initializer value). This lets
/// <c>[RequiresTalent(&lt;Hero&gt;Talents.&lt;Name&gt;)]</c> reference native talent ids as compile-time
/// constants - e.g. <c>ArdeosTalents.RollingFlames == 226</c>.
/// </summary>
/// <remarks>
/// The companion class is emitted in the parent namespace (<c>FellowshipAnalyzer.Core.Common.Spells</c>),
/// so consuming code adds <c>using FellowshipAnalyzer.Core.Common.Spells;</c> to reach <c>{Hero}Talents</c>.
/// </remarks>
[Generator]
public sealed class TalentIdConstantsGenerator : IIncrementalGenerator
{
    private const string TalentsClassName = "Talents";
    private const string TalentTypeName = "Talent";
    private const string SpellsNamespaceRoot = "FellowshipAnalyzer.Core.Common.Spells.";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var talentClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, ct) => GetTalentClassInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(talentClasses, Emit);
    }

    private static bool IsCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax classDecl && classDecl.Identifier.ValueText == TalentsClassName;

    private static TalentClassInfo? GetTalentClassInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
            return null;

        var ns = symbol.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingNamespace.ToDisplayString()
            : string.Empty;

        if (!ns.StartsWith(SpellsNamespaceRoot, StringComparison.Ordinal))
            return null;

        var heroSegment = ns.Substring(SpellsNamespaceRoot.Length);
        if (heroSegment.Length == 0 || heroSegment.IndexOf('.') >= 0)
            return null;

        var parentNamespace = ns.Substring(0, SpellsNamespaceRoot.Length - 1);

        var consts = ImmutableArray.CreateBuilder<TalentConst>();
        foreach (var member in symbol.GetMembers())
        {
            if (member is not IPropertySymbol { IsStatic: true } prop) continue;
            if (prop.Type.Name != TalentTypeName) continue;
            if (!TryReadTalentId(prop, ct, out var id)) continue;

            consts.Add(new TalentConst(prop.Name, id));
        }

        if (consts.Count == 0)
            return null;

        consts.Sort(static (a, b) => string.CompareOrdinal(a.Name, b.Name));

        return new TalentClassInfo(parentNamespace, heroSegment, ns, consts.ToImmutable());
    }

    private static bool TryReadTalentId(IPropertySymbol property, CancellationToken ct, out int id)
    {
        id = 0;
        if (property.DeclaringSyntaxReferences.Length == 0) return false;
        if (property.DeclaringSyntaxReferences[0].GetSyntax(ct) is not PropertyDeclarationSyntax pds) return false;
        if (pds.Initializer is null) return false;

        var initExpr = pds.Initializer.Value switch
        {
            ObjectCreationExpressionSyntax o => o.Initializer,
            ImplicitObjectCreationExpressionSyntax io => io.Initializer,
            _ => null,
        };
        if (initExpr is null) return false;

        foreach (var e in initExpr.Expressions)
        {
            if (e is AssignmentExpressionSyntax { Left: IdentifierNameSyntax { Identifier.ValueText: "Id" } } a
                && a.Right is LiteralExpressionSyntax { Token.Value: int idValue })
            {
                id = idValue;
                return true;
            }
        }
        return false;
    }

    private static void Emit(SourceProductionContext ctx, TalentClassInfo info)
    {
        var className = info.HeroName + TalentsClassName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace " + info.ParentNamespace + ";");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time native talent ids for <see cref=\"global::" + info.TalentsNamespace + ".Talents\"/>,");
        sb.AppendLine("/// generated so <c>[RequiresTalent(...)]</c> can reference talents as constants.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class " + className);
        sb.AppendLine("{");
        foreach (var c in info.Consts)
        {
            sb.AppendLine("    /// <summary>Native talent id of <c>" + c.Name + "</c>.</summary>");
            sb.AppendLine("    public const int " + c.Name + " = " + c.Id.ToString(CultureInfo.InvariantCulture) + ";");
        }
        sb.AppendLine("}");

        ctx.AddSource(className + ".g.cs", sb.ToString());
    }

    private sealed class TalentClassInfo(
        string ParentNamespace,
        string HeroName,
        string TalentsNamespace,
        ImmutableArray<TalentConst> Consts)
    {
        public string ParentNamespace { get; } = ParentNamespace;
        public string HeroName { get; } = HeroName;
        public string TalentsNamespace { get; } = TalentsNamespace;
        public ImmutableArray<TalentConst> Consts { get; } = Consts;
    }

    private readonly struct TalentConst(string Name, int Id)
    {
        public string Name { get; } = Name;
        public int Id { get; } = Id;
    }
}
