query GetReport($code: String!) {
  reportData {
    report(code: $code) {
      title
      startTime
      endTime
      fights {
        id
        name
        encounterID
        kill
        startTime
        endTime
        difficulty
        friendlyPlayers
        inProgress
        fightPercentage
        enemyNPCs {
          id
          gameID
          instanceCount
          groupCount
          petOwner
        }
        dungeonPulls {
          id
          encounterID
          kill
          startTime
          endTime
          name
          enemyNPCs {
            id
            gameID
            minimumInstanceID
            maximumInstanceID
            minimumInstanceGroupID
            maximumInstanceGroupID
          }
        }
      }
      masterData {
        actors {
          id
          name
          type
          subType
          server
          icon
        }
      }
    }
  }
}
