<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="sasscompiler.json" CopyToPublishDirectory="Never" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\FellowshipAnalyzer.Core\FellowshipAnalyzer.Core.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="AspNetCore.SassCompiler" Version="1.77.8" />
		<PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.7" />
	</ItemGroup>

</Project>
