<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StrawberryShake.Server" />
  </ItemGroup>

  <ItemGroup>
    <GraphQL Include="schema.graphql" />
    <GraphQL Include="schema.extensions.graphql" />
    <GraphQL Include="GraphQL/**/*.graphql" />
  </ItemGroup>

</Project>
