<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
		<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<PropertyGroup Condition="'$(StandaloneWasmHost)' == 'true'">
		<DefineConstants>$(DefineConstants);STANDALONE_WASM</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<RunAOTCompilation>true</RunAOTCompilation>
	</PropertyGroup>

	<PropertyGroup Condition="'$(RunAOTCompilation)' == 'true'">
		<DefineConstants>$(DefineConstants);WASM_AOT_BUILD</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\FellowshipAnalyzer.Components\FellowshipAnalyzer.Components.csproj" />
		<ProjectReference Include="..\..\FellowshipAnalyzer.Core\FellowshipAnalyzer.Core.csproj" />
		<ProjectReference Include="..\..\FellowshipAnalyzer.Heroes.Rime\FellowshipAnalyzer.Heroes.Rime.csproj" />
		<ProjectReference Include="..\..\FellowshipAnalyzer.Generators\FellowshipAnalyzer.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="sasscompiler.json" CopyToPublishDirectory="Never" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="AspNetCore.SassCompiler" Version="1.77.8" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
	</ItemGroup>

</Project>
