schema {
  query: Query
}

scalar Float
scalar Boolean
scalar Int
scalar String
scalar JSON

type Query {
  characterData: CharacterData
  reportData: ReportData
}

type CharacterData {
  character(id: Int, name: String, serverSlug: String, serverRegion: String): Character
}

type Character {
  id: Int!
  name: String!
  recentReports: ReportPagination
}

type ReportPagination {
  data: [Report]
  has_more_pages: Boolean!
}

type ReportData {
  report(code: String!): Report
}

type Report {
  code: String!
  title: String
  startTime: Float!
  endTime: Float
  fights(fightIDs: [Int]): [ReportFight]
  masterData(translate: Boolean): ReportMasterData
  events(fightIDs: [Int], sourceID: Int, includeResources: Boolean): ReportEventPaginator
}

type ReportFight {
  id: Int!
  name: String!
  encounterID: Int!
  kill: Boolean
  startTime: Float!
  endTime: Float!
  difficulty: Int
  friendlyPlayers: [Int]
  fightPercentage: Float
  inProgress: Boolean!
  dungeonPulls: [ReportDungeonPull]
}

type ReportDungeonPull {
  encounterID: Int!
  startTime: Float!
  endTime: Float!
  name: String!
}

type ReportEventPaginator {
  data: JSON
}

type ReportMasterData {
  abilities: [ReportAbility]
  actors: [ReportActor]
}

type ReportAbility {
  gameID: Int!
  name: String!
  icon: String!
  type: String!
}

type ReportActor {
  id: Int!
  name: String!
  type: String!
  subType: String
  server: String
  icon: String
}
