<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include=".\..\FellowshipAnalyzer.Core\FellowshipAnalyzer.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="StrawberryShake.Server" />
	</ItemGroup>

	<ItemGroup>
		<GraphQL Include="schema.graphql" />
		<GraphQL Include="schema.extensions.graphql" />
		<GraphQL Include="API/GraphQL/**/*.graphql" />
	</ItemGroup>

</Project>
